name: medicine_reminder
description: A simple offline medicine reminder app for elderly users.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  record: ^5.0.4
  audioplayers: ^5.2.1
  flutter_local_notifications: ^16.1.0
  permission_handler: ^11.1.0
  vibration: ^1.8.4
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
