name: Build Professional APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Fresh Android Setup
        # Humne '--force' hata diya hai kyunki 'rm -rf' pehle hi folder saaf kar dega
        run: |
          rm -rf android
          flutter create . --platforms android

      - name: Get Packages
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EasyLoan-APK
          path: build/app/outputs/flutter-apk/app-debug.apk
